package com.hx.mapper;

import com.hx.model.Csfzk;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
//流量检测映射层
public interface CsfzkMapper {
    @Delete({
        "delete from csfzk",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into csfzk (id, zch, ",
        "tmh, scdh, qjh, ",
        "jysj, wd, sd, ",
        "jyry, shry, zgry, ",
        "dqyl, ysys, zyls, ",
        "jl, wg, mfx, ",
        "xx, cfx, jyrq, ",
        "yxrq, zzfj, bw, ",
        "ccbh, sccj, xh, ",
        "dj, wtdw, wtdwdz, ",
        "zsh, zzbh, maxl, ",
        "max2l, minl, maxbz, ",
        "maxb1, maxb2, maxb3, ",
        "maxb4, maxb5, maxb6, ",
        "maxb7, maxb8, maxb9, ",
        "maxb0, max, maxcz, ",
        "max1, max2, max3, ",
        "max4, max5, max6, ",
        "max7, max8, max9, ",
        "max0, maxbzyl1, ",
        "maxbzyl2, maxbzyl3, ",
        "maxbzyl4, maxbzyl5, ",
        "maxbzyl6, maxbzyl7, ",
        "maxbzyl8, maxbzyl9, ",
        "maxbzyl0, maxbzwd1, ",
        "maxbzwd2, maxbzwd3, ",
        "maxbzwd4, maxbzwd5, ",
        "maxbzwd6, maxbzwd7, ",
        "maxbzwd8, maxbzwd9, ",
        "maxbzwd0, maxbyl1, ",
        "maxbyl2, maxbyl3, ",
        "maxbyl4, maxbyl5, ",
        "maxbyl6, maxbyl7, ",
        "maxbyl8, maxbyl9, ",
        "maxbyl0, maxbwd1, ",
        "maxbwd2, maxbwd3, ",
        "maxbwd4, maxbwd5, ",
        "maxbwd6, maxbwd7, ",
        "maxbwd8, maxbwd9, ",
        "maxbwd0, max02bz, ",
        "max02b1, max02b2, ",
        "max02b3, max02b4, ",
        "max02b5, max02b6, ",
        "max02b7, max02b8, ",
        "max02b9, max02b0, ",
        "max02, max02cz, ",
        "max021, max022, ",
        "max023, max024, ",
        "max025, max026, ",
        "max027, max028, ",
        "max029, max020, ",
        "max02bzyl1, max02bzyl2, ",
        "max02bzyl3, max02bzyl4, ",
        "max02bzyl5, max02bzyl6, ",
        "max02bzyl7, max02bzyl8, ",
        "max02bzyl9, max02bzyl0, ",
        "max02bzwd1, max02bzwd2, ",
        "max02bzwd3, max02bzwd4, ",
        "max02bzwd5, max02bzwd6, ",
        "max02bzwd7, max02bzwd8, ",
        "max02bzwd9, max02bzwd0, ",
        "max02byl1, max02byl2, ",
        "max02byl3, max02byl4, ",
        "max02byl5, max02byl6, ",
        "max02byl7, max02byl8, ",
        "max02byl9, max02byl0, ",
        "max02bwd1, max02bwd2, ",
        "max02bwd3, max02bwd4, ",
        "max02bwd5, max02bwd6, ",
        "max02bwd7, max02bwd8, ",
        "max02bwd9, max02bwd0, ",
        "minbz, minb1, minb2, ",
        "minb3, minb4, minb5, ",
        "minb6, minb7, minb8, ",
        "minb9, minb0, mincz, ",
        "min, min1, min2, ",
        "min3, min4, min5, ",
        "min6, min7, min8, ",
        "min9, min0, minbzyl1, ",
        "minbzyl2, minbzyl3, ",
        "minbzyl4, minbzyl5, ",
        "minbzyl6, minbzyl7, ",
        "minbzyl8, minbzyl9, ",
        "minbzyl0, minbzwd1, ",
        "minbzwd2, minbzwd3, ",
        "minbzwd4, minbzwd5, ",
        "minbzwd6, minbzwd7, ",
        "minbzwd8, minbzwd9, ",
        "minbzwd0, minbyl1, ",
        "minbyl2, minbyl3, ",
        "minbyl4, minbyl5, ",
        "minbyl6, minbyl7, ",
        "minbyl8, minbyl9, ",
        "minbyl0, minbwd1, ",
        "minbwd2, minbwd3, ",
        "minbwd4, minbwd5, ",
        "minbwd6, minbwd7, ",
        "minbwd8, minbwd9, ",
        "minbwd0, bz, dlwcx, ",
        "zlwcx, xlwcx, dlwcjl, ",
        "zlwcjl, xlwcjl, ",
        "maxll, midll, minll, ",
        "maxcs, max02cs, ",
        "mincs)",
        "values (#{id,jdbcType=BIGINT}, #{zch,jdbcType=VARCHAR}, ",
        "#{tmh,jdbcType=VARCHAR}, #{scdh,jdbcType=VARCHAR}, #{qjh,jdbcType=VARCHAR}, ",
        "#{jysj,jdbcType=TIMESTAMP}, #{wd,jdbcType=NUMERIC}, #{sd,jdbcType=VARCHAR}, ",
        "#{jyry,jdbcType=VARCHAR}, #{shry,jdbcType=VARCHAR}, #{zgry,jdbcType=VARCHAR}, ",
        "#{dqyl,jdbcType=NUMERIC}, #{ysys,jdbcType=VARCHAR}, #{zyls,jdbcType=NUMERIC}, ",
        "#{jl,jdbcType=VARCHAR}, #{wg,jdbcType=VARCHAR}, #{mfx,jdbcType=VARCHAR}, ",
        "#{xx,jdbcType=VARCHAR}, #{cfx,jdbcType=VARCHAR}, #{jyrq,jdbcType=TIMESTAMP}, ",
        "#{yxrq,jdbcType=TIMESTAMP}, #{zzfj,jdbcType=VARCHAR}, #{bw,jdbcType=VARCHAR}, ",
        "#{ccbh,jdbcType=VARCHAR}, #{sccj,jdbcType=VARCHAR}, #{xh,jdbcType=VARCHAR}, ",
        "#{dj,jdbcType=VARCHAR}, #{wtdw,jdbcType=VARCHAR}, #{wtdwdz,jdbcType=VARCHAR}, ",
        "#{zsh,jdbcType=VARCHAR}, #{zzbh,jdbcType=VARCHAR}, #{maxl,jdbcType=NUMERIC}, ",
        "#{max2l,jdbcType=NUMERIC}, #{minl,jdbcType=NUMERIC}, #{maxbz,jdbcType=VARCHAR}, ",
        "#{maxb1,jdbcType=NUMERIC}, #{maxb2,jdbcType=NUMERIC}, #{maxb3,jdbcType=NUMERIC}, ",
        "#{maxb4,jdbcType=NUMERIC}, #{maxb5,jdbcType=NUMERIC}, #{maxb6,jdbcType=NUMERIC}, ",
        "#{maxb7,jdbcType=NUMERIC}, #{maxb8,jdbcType=NUMERIC}, #{maxb9,jdbcType=NUMERIC}, ",
        "#{maxb0,jdbcType=NUMERIC}, #{max,jdbcType=NUMERIC}, #{maxcz,jdbcType=NUMERIC}, ",
        "#{max1,jdbcType=NUMERIC}, #{max2,jdbcType=NUMERIC}, #{max3,jdbcType=NUMERIC}, ",
        "#{max4,jdbcType=NUMERIC}, #{max5,jdbcType=NUMERIC}, #{max6,jdbcType=NUMERIC}, ",
        "#{max7,jdbcType=NUMERIC}, #{max8,jdbcType=NUMERIC}, #{max9,jdbcType=NUMERIC}, ",
        "#{max0,jdbcType=NUMERIC}, #{maxbzyl1,jdbcType=NUMERIC}, ",
        "#{maxbzyl2,jdbcType=NUMERIC}, #{maxbzyl3,jdbcType=NUMERIC}, ",
        "#{maxbzyl4,jdbcType=NUMERIC}, #{maxbzyl5,jdbcType=NUMERIC}, ",
        "#{maxbzyl6,jdbcType=NUMERIC}, #{maxbzyl7,jdbcType=NUMERIC}, ",
        "#{maxbzyl8,jdbcType=NUMERIC}, #{maxbzyl9,jdbcType=NUMERIC}, ",
        "#{maxbzyl0,jdbcType=NUMERIC}, #{maxbzwd1,jdbcType=NUMERIC}, ",
        "#{maxbzwd2,jdbcType=NUMERIC}, #{maxbzwd3,jdbcType=NUMERIC}, ",
        "#{maxbzwd4,jdbcType=NUMERIC}, #{maxbzwd5,jdbcType=NUMERIC}, ",
        "#{maxbzwd6,jdbcType=NUMERIC}, #{maxbzwd7,jdbcType=NUMERIC}, ",
        "#{maxbzwd8,jdbcType=NUMERIC}, #{maxbzwd9,jdbcType=NUMERIC}, ",
        "#{maxbzwd0,jdbcType=NUMERIC}, #{maxbyl1,jdbcType=NUMERIC}, ",
        "#{maxbyl2,jdbcType=NUMERIC}, #{maxbyl3,jdbcType=NUMERIC}, ",
        "#{maxbyl4,jdbcType=NUMERIC}, #{maxbyl5,jdbcType=NUMERIC}, ",
        "#{maxbyl6,jdbcType=NUMERIC}, #{maxbyl7,jdbcType=NUMERIC}, ",
        "#{maxbyl8,jdbcType=NUMERIC}, #{maxbyl9,jdbcType=NUMERIC}, ",
        "#{maxbyl0,jdbcType=NUMERIC}, #{maxbwd1,jdbcType=NUMERIC}, ",
        "#{maxbwd2,jdbcType=NUMERIC}, #{maxbwd3,jdbcType=NUMERIC}, ",
        "#{maxbwd4,jdbcType=NUMERIC}, #{maxbwd5,jdbcType=NUMERIC}, ",
        "#{maxbwd6,jdbcType=NUMERIC}, #{maxbwd7,jdbcType=NUMERIC}, ",
        "#{maxbwd8,jdbcType=NUMERIC}, #{maxbwd9,jdbcType=NUMERIC}, ",
        "#{maxbwd0,jdbcType=NUMERIC}, #{max02bz,jdbcType=VARCHAR}, ",
        "#{max02b1,jdbcType=NUMERIC}, #{max02b2,jdbcType=NUMERIC}, ",
        "#{max02b3,jdbcType=NUMERIC}, #{max02b4,jdbcType=NUMERIC}, ",
        "#{max02b5,jdbcType=NUMERIC}, #{max02b6,jdbcType=NUMERIC}, ",
        "#{max02b7,jdbcType=NUMERIC}, #{max02b8,jdbcType=NUMERIC}, ",
        "#{max02b9,jdbcType=NUMERIC}, #{max02b0,jdbcType=NUMERIC}, ",
        "#{max02,jdbcType=NUMERIC}, #{max02cz,jdbcType=NUMERIC}, ",
        "#{max021,jdbcType=NUMERIC}, #{max022,jdbcType=NUMERIC}, ",
        "#{max023,jdbcType=NUMERIC}, #{max024,jdbcType=NUMERIC}, ",
        "#{max025,jdbcType=NUMERIC}, #{max026,jdbcType=NUMERIC}, ",
        "#{max027,jdbcType=NUMERIC}, #{max028,jdbcType=NUMERIC}, ",
        "#{max029,jdbcType=NUMERIC}, #{max020,jdbcType=NUMERIC}, ",
        "#{max02bzyl1,jdbcType=NUMERIC}, #{max02bzyl2,jdbcType=NUMERIC}, ",
        "#{max02bzyl3,jdbcType=NUMERIC}, #{max02bzyl4,jdbcType=NUMERIC}, ",
        "#{max02bzyl5,jdbcType=NUMERIC}, #{max02bzyl6,jdbcType=NUMERIC}, ",
        "#{max02bzyl7,jdbcType=NUMERIC}, #{max02bzyl8,jdbcType=NUMERIC}, ",
        "#{max02bzyl9,jdbcType=NUMERIC}, #{max02bzyl0,jdbcType=NUMERIC}, ",
        "#{max02bzwd1,jdbcType=NUMERIC}, #{max02bzwd2,jdbcType=NUMERIC}, ",
        "#{max02bzwd3,jdbcType=NUMERIC}, #{max02bzwd4,jdbcType=NUMERIC}, ",
        "#{max02bzwd5,jdbcType=NUMERIC}, #{max02bzwd6,jdbcType=NUMERIC}, ",
        "#{max02bzwd7,jdbcType=NUMERIC}, #{max02bzwd8,jdbcType=NUMERIC}, ",
        "#{max02bzwd9,jdbcType=NUMERIC}, #{max02bzwd0,jdbcType=NUMERIC}, ",
        "#{max02byl1,jdbcType=NUMERIC}, #{max02byl2,jdbcType=NUMERIC}, ",
        "#{max02byl3,jdbcType=NUMERIC}, #{max02byl4,jdbcType=NUMERIC}, ",
        "#{max02byl5,jdbcType=NUMERIC}, #{max02byl6,jdbcType=NUMERIC}, ",
        "#{max02byl7,jdbcType=NUMERIC}, #{max02byl8,jdbcType=NUMERIC}, ",
        "#{max02byl9,jdbcType=NUMERIC}, #{max02byl0,jdbcType=NUMERIC}, ",
        "#{max02bwd1,jdbcType=NUMERIC}, #{max02bwd2,jdbcType=NUMERIC}, ",
        "#{max02bwd3,jdbcType=NUMERIC}, #{max02bwd4,jdbcType=NUMERIC}, ",
        "#{max02bwd5,jdbcType=NUMERIC}, #{max02bwd6,jdbcType=NUMERIC}, ",
        "#{max02bwd7,jdbcType=NUMERIC}, #{max02bwd8,jdbcType=NUMERIC}, ",
        "#{max02bwd9,jdbcType=NUMERIC}, #{max02bwd0,jdbcType=NUMERIC}, ",
        "#{minbz,jdbcType=VARCHAR}, #{minb1,jdbcType=NUMERIC}, #{minb2,jdbcType=NUMERIC}, ",
        "#{minb3,jdbcType=NUMERIC}, #{minb4,jdbcType=NUMERIC}, #{minb5,jdbcType=NUMERIC}, ",
        "#{minb6,jdbcType=NUMERIC}, #{minb7,jdbcType=NUMERIC}, #{minb8,jdbcType=NUMERIC}, ",
        "#{minb9,jdbcType=NUMERIC}, #{minb0,jdbcType=NUMERIC}, #{mincz,jdbcType=NUMERIC}, ",
        "#{min,jdbcType=VARCHAR}, #{min1,jdbcType=VARCHAR}, #{min2,jdbcType=NUMERIC}, ",
        "#{min3,jdbcType=NUMERIC}, #{min4,jdbcType=NUMERIC}, #{min5,jdbcType=NUMERIC}, ",
        "#{min6,jdbcType=NUMERIC}, #{min7,jdbcType=NUMERIC}, #{min8,jdbcType=NUMERIC}, ",
        "#{min9,jdbcType=NUMERIC}, #{min0,jdbcType=NUMERIC}, #{minbzyl1,jdbcType=NUMERIC}, ",
        "#{minbzyl2,jdbcType=NUMERIC}, #{minbzyl3,jdbcType=NUMERIC}, ",
        "#{minbzyl4,jdbcType=NUMERIC}, #{minbzyl5,jdbcType=NUMERIC}, ",
        "#{minbzyl6,jdbcType=NUMERIC}, #{minbzyl7,jdbcType=NUMERIC}, ",
        "#{minbzyl8,jdbcType=NUMERIC}, #{minbzyl9,jdbcType=NUMERIC}, ",
        "#{minbzyl0,jdbcType=NUMERIC}, #{minbzwd1,jdbcType=NUMERIC}, ",
        "#{minbzwd2,jdbcType=NUMERIC}, #{minbzwd3,jdbcType=NUMERIC}, ",
        "#{minbzwd4,jdbcType=NUMERIC}, #{minbzwd5,jdbcType=NUMERIC}, ",
        "#{minbzwd6,jdbcType=NUMERIC}, #{minbzwd7,jdbcType=NUMERIC}, ",
        "#{minbzwd8,jdbcType=NUMERIC}, #{minbzwd9,jdbcType=NUMERIC}, ",
        "#{minbzwd0,jdbcType=NUMERIC}, #{minbyl1,jdbcType=NUMERIC}, ",
        "#{minbyl2,jdbcType=NUMERIC}, #{minbyl3,jdbcType=NUMERIC}, ",
        "#{minbyl4,jdbcType=NUMERIC}, #{minbyl5,jdbcType=NUMERIC}, ",
        "#{minbyl6,jdbcType=NUMERIC}, #{minbyl7,jdbcType=NUMERIC}, ",
        "#{minbyl8,jdbcType=NUMERIC}, #{minbyl9,jdbcType=NUMERIC}, ",
        "#{minbyl0,jdbcType=NUMERIC}, #{minbwd1,jdbcType=NUMERIC}, ",
        "#{minbwd2,jdbcType=NUMERIC}, #{minbwd3,jdbcType=NUMERIC}, ",
        "#{minbwd4,jdbcType=NUMERIC}, #{minbwd5,jdbcType=NUMERIC}, ",
        "#{minbwd6,jdbcType=NUMERIC}, #{minbwd7,jdbcType=NUMERIC}, ",
        "#{minbwd8,jdbcType=NUMERIC}, #{minbwd9,jdbcType=NUMERIC}, ",
        "#{minbwd0,jdbcType=NUMERIC}, #{bz,jdbcType=VARCHAR}, #{dlwcx,jdbcType=VARCHAR}, ",
        "#{zlwcx,jdbcType=VARCHAR}, #{xlwcx,jdbcType=VARCHAR}, #{dlwcjl,jdbcType=VARCHAR}, ",
        "#{zlwcjl,jdbcType=VARCHAR}, #{xlwcjl,jdbcType=VARCHAR}, ",
        "#{maxll,jdbcType=VARCHAR}, #{midll,jdbcType=VARCHAR}, #{minll,jdbcType=VARCHAR}, ",
        "#{maxcs,jdbcType=VARCHAR}, #{max02cs,jdbcType=VARCHAR}, ",
        "#{mincs,jdbcType=VARCHAR})"
    })
    int insert(Csfzk record);

    @InsertProvider(type=CsfzkSqlProvider.class, method="insertSelective")
    int insertSelective(Csfzk record);

    @Select({
        "select",
        "id, zch, tmh, scdh, qjh, jysj, wd, sd, jyry, shry, zgry, dqyl, ysys, zyls, jl, ",
        "wg, mfx, xx, cfx, jyrq, yxrq, zzfj, bw, ccbh, sccj, xh, dj, wtdw, wtdwdz, zsh, ",
        "zzbh, maxl, max2l, minl, maxbz, maxb1, maxb2, maxb3, maxb4, maxb5, maxb6, maxb7, ",
        "maxb8, maxb9, maxb0, max, maxcz, max1, max2, max3, max4, max5, max6, max7, max8, ",
        "max9, max0, maxbzyl1, maxbzyl2, maxbzyl3, maxbzyl4, maxbzyl5, maxbzyl6, maxbzyl7, ",
        "maxbzyl8, maxbzyl9, maxbzyl0, maxbzwd1, maxbzwd2, maxbzwd3, maxbzwd4, maxbzwd5, ",
        "maxbzwd6, maxbzwd7, maxbzwd8, maxbzwd9, maxbzwd0, maxbyl1, maxbyl2, maxbyl3, ",
        "maxbyl4, maxbyl5, maxbyl6, maxbyl7, maxbyl8, maxbyl9, maxbyl0, maxbwd1, maxbwd2, ",
        "maxbwd3, maxbwd4, maxbwd5, maxbwd6, maxbwd7, maxbwd8, maxbwd9, maxbwd0, max02bz, ",
        "max02b1, max02b2, max02b3, max02b4, max02b5, max02b6, max02b7, max02b8, max02b9, ",
        "max02b0, max02, max02cz, max021, max022, max023, max024, max025, max026, max027, ",
        "max028, max029, max020, max02bzyl1, max02bzyl2, max02bzyl3, max02bzyl4, max02bzyl5, ",
        "max02bzyl6, max02bzyl7, max02bzyl8, max02bzyl9, max02bzyl0, max02bzwd1, max02bzwd2, ",
        "max02bzwd3, max02bzwd4, max02bzwd5, max02bzwd6, max02bzwd7, max02bzwd8, max02bzwd9, ",
        "max02bzwd0, max02byl1, max02byl2, max02byl3, max02byl4, max02byl5, max02byl6, ",
        "max02byl7, max02byl8, max02byl9, max02byl0, max02bwd1, max02bwd2, max02bwd3, ",
        "max02bwd4, max02bwd5, max02bwd6, max02bwd7, max02bwd8, max02bwd9, max02bwd0, ",
        "minbz, minb1, minb2, minb3, minb4, minb5, minb6, minb7, minb8, minb9, minb0, ",
        "mincz, min, min1, min2, min3, min4, min5, min6, min7, min8, min9, min0, minbzyl1, ",
        "minbzyl2, minbzyl3, minbzyl4, minbzyl5, minbzyl6, minbzyl7, minbzyl8, minbzyl9, ",
        "minbzyl0, minbzwd1, minbzwd2, minbzwd3, minbzwd4, minbzwd5, minbzwd6, minbzwd7, ",
        "minbzwd8, minbzwd9, minbzwd0, minbyl1, minbyl2, minbyl3, minbyl4, minbyl5, minbyl6, ",
        "minbyl7, minbyl8, minbyl9, minbyl0, minbwd1, minbwd2, minbwd3, minbwd4, minbwd5, ",
        "minbwd6, minbwd7, minbwd8, minbwd9, minbwd0, bz, dlwcx, zlwcx, xlwcx, dlwcjl, ",
        "zlwcjl, xlwcjl, maxll, midll, minll, maxcs, max02cs, mincs",
        "from csfzk",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="zch", property="zch", jdbcType=JdbcType.VARCHAR),
        @Result(column="tmh", property="tmh", jdbcType=JdbcType.VARCHAR),
        @Result(column="scdh", property="scdh", jdbcType=JdbcType.VARCHAR),
        @Result(column="qjh", property="qjh", jdbcType=JdbcType.VARCHAR),
        @Result(column="jysj", property="jysj", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="wd", property="wd", jdbcType=JdbcType.NUMERIC),
        @Result(column="sd", property="sd", jdbcType=JdbcType.VARCHAR),
        @Result(column="jyry", property="jyry", jdbcType=JdbcType.VARCHAR),
        @Result(column="shry", property="shry", jdbcType=JdbcType.VARCHAR),
        @Result(column="zgry", property="zgry", jdbcType=JdbcType.VARCHAR),
        @Result(column="dqyl", property="dqyl", jdbcType=JdbcType.NUMERIC),
        @Result(column="ysys", property="ysys", jdbcType=JdbcType.VARCHAR),
        @Result(column="zyls", property="zyls", jdbcType=JdbcType.NUMERIC),
        @Result(column="jl", property="jl", jdbcType=JdbcType.VARCHAR),
        @Result(column="wg", property="wg", jdbcType=JdbcType.VARCHAR),
        @Result(column="mfx", property="mfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="xx", property="xx", jdbcType=JdbcType.VARCHAR),
        @Result(column="cfx", property="cfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="jyrq", property="jyrq", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="yxrq", property="yxrq", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="zzfj", property="zzfj", jdbcType=JdbcType.VARCHAR),
        @Result(column="bw", property="bw", jdbcType=JdbcType.VARCHAR),
        @Result(column="ccbh", property="ccbh", jdbcType=JdbcType.VARCHAR),
        @Result(column="sccj", property="sccj", jdbcType=JdbcType.VARCHAR),
        @Result(column="xh", property="xh", jdbcType=JdbcType.VARCHAR),
        @Result(column="dj", property="dj", jdbcType=JdbcType.VARCHAR),
        @Result(column="wtdw", property="wtdw", jdbcType=JdbcType.VARCHAR),
        @Result(column="wtdwdz", property="wtdwdz", jdbcType=JdbcType.VARCHAR),
        @Result(column="zsh", property="zsh", jdbcType=JdbcType.VARCHAR),
        @Result(column="zzbh", property="zzbh", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxl", property="maxl", jdbcType=JdbcType.NUMERIC),
        @Result(column="max2l", property="max2l", jdbcType=JdbcType.NUMERIC),
        @Result(column="minl", property="minl", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbz", property="maxbz", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxb1", property="maxb1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb2", property="maxb2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb3", property="maxb3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb4", property="maxb4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb5", property="maxb5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb6", property="maxb6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb7", property="maxb7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb8", property="maxb8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb9", property="maxb9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb0", property="maxb0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max", property="max", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxcz", property="maxcz", jdbcType=JdbcType.NUMERIC),
        @Result(column="max1", property="max1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max2", property="max2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max3", property="max3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max4", property="max4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max5", property="max5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max6", property="max6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max7", property="max7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max8", property="max8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max9", property="max9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max0", property="max0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl1", property="maxbzyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl2", property="maxbzyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl3", property="maxbzyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl4", property="maxbzyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl5", property="maxbzyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl6", property="maxbzyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl7", property="maxbzyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl8", property="maxbzyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl9", property="maxbzyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl0", property="maxbzyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd1", property="maxbzwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd2", property="maxbzwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd3", property="maxbzwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd4", property="maxbzwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd5", property="maxbzwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd6", property="maxbzwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd7", property="maxbzwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd8", property="maxbzwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd9", property="maxbzwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd0", property="maxbzwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl1", property="maxbyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl2", property="maxbyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl3", property="maxbyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl4", property="maxbyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl5", property="maxbyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl6", property="maxbyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl7", property="maxbyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl8", property="maxbyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl9", property="maxbyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl0", property="maxbyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd1", property="maxbwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd2", property="maxbwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd3", property="maxbwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd4", property="maxbwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd5", property="maxbwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd6", property="maxbwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd7", property="maxbwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd8", property="maxbwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd9", property="maxbwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd0", property="maxbwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bz", property="max02bz", jdbcType=JdbcType.VARCHAR),
        @Result(column="max02b1", property="max02b1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b2", property="max02b2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b3", property="max02b3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b4", property="max02b4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b5", property="max02b5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b6", property="max02b6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b7", property="max02b7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b8", property="max02b8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b9", property="max02b9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b0", property="max02b0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02", property="max02", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02cz", property="max02cz", jdbcType=JdbcType.NUMERIC),
        @Result(column="max021", property="max021", jdbcType=JdbcType.NUMERIC),
        @Result(column="max022", property="max022", jdbcType=JdbcType.NUMERIC),
        @Result(column="max023", property="max023", jdbcType=JdbcType.NUMERIC),
        @Result(column="max024", property="max024", jdbcType=JdbcType.NUMERIC),
        @Result(column="max025", property="max025", jdbcType=JdbcType.NUMERIC),
        @Result(column="max026", property="max026", jdbcType=JdbcType.NUMERIC),
        @Result(column="max027", property="max027", jdbcType=JdbcType.NUMERIC),
        @Result(column="max028", property="max028", jdbcType=JdbcType.NUMERIC),
        @Result(column="max029", property="max029", jdbcType=JdbcType.NUMERIC),
        @Result(column="max020", property="max020", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl1", property="max02bzyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl2", property="max02bzyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl3", property="max02bzyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl4", property="max02bzyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl5", property="max02bzyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl6", property="max02bzyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl7", property="max02bzyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl8", property="max02bzyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl9", property="max02bzyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl0", property="max02bzyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd1", property="max02bzwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd2", property="max02bzwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd3", property="max02bzwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd4", property="max02bzwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd5", property="max02bzwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd6", property="max02bzwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd7", property="max02bzwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd8", property="max02bzwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd9", property="max02bzwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd0", property="max02bzwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl1", property="max02byl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl2", property="max02byl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl3", property="max02byl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl4", property="max02byl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl5", property="max02byl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl6", property="max02byl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl7", property="max02byl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl8", property="max02byl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl9", property="max02byl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl0", property="max02byl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd1", property="max02bwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd2", property="max02bwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd3", property="max02bwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd4", property="max02bwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd5", property="max02bwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd6", property="max02bwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd7", property="max02bwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd8", property="max02bwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd9", property="max02bwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd0", property="max02bwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbz", property="minbz", jdbcType=JdbcType.VARCHAR),
        @Result(column="minb1", property="minb1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb2", property="minb2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb3", property="minb3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb4", property="minb4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb5", property="minb5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb6", property="minb6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb7", property="minb7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb8", property="minb8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb9", property="minb9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb0", property="minb0", jdbcType=JdbcType.NUMERIC),
        @Result(column="mincz", property="mincz", jdbcType=JdbcType.NUMERIC),
        @Result(column="min", property="min", jdbcType=JdbcType.VARCHAR),
        @Result(column="min1", property="min1", jdbcType=JdbcType.VARCHAR),
        @Result(column="min2", property="min2", jdbcType=JdbcType.NUMERIC),
        @Result(column="min3", property="min3", jdbcType=JdbcType.NUMERIC),
        @Result(column="min4", property="min4", jdbcType=JdbcType.NUMERIC),
        @Result(column="min5", property="min5", jdbcType=JdbcType.NUMERIC),
        @Result(column="min6", property="min6", jdbcType=JdbcType.NUMERIC),
        @Result(column="min7", property="min7", jdbcType=JdbcType.NUMERIC),
        @Result(column="min8", property="min8", jdbcType=JdbcType.NUMERIC),
        @Result(column="min9", property="min9", jdbcType=JdbcType.NUMERIC),
        @Result(column="min0", property="min0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl1", property="minbzyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl2", property="minbzyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl3", property="minbzyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl4", property="minbzyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl5", property="minbzyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl6", property="minbzyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl7", property="minbzyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl8", property="minbzyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl9", property="minbzyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl0", property="minbzyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd1", property="minbzwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd2", property="minbzwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd3", property="minbzwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd4", property="minbzwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd5", property="minbzwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd6", property="minbzwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd7", property="minbzwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd8", property="minbzwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd9", property="minbzwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd0", property="minbzwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl1", property="minbyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl2", property="minbyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl3", property="minbyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl4", property="minbyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl5", property="minbyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl6", property="minbyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl7", property="minbyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl8", property="minbyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl9", property="minbyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl0", property="minbyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd1", property="minbwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd2", property="minbwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd3", property="minbwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd4", property="minbwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd5", property="minbwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd6", property="minbwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd7", property="minbwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd8", property="minbwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd9", property="minbwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd0", property="minbwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="bz", property="bz", jdbcType=JdbcType.VARCHAR),
        @Result(column="dlwcx", property="dlwcx", jdbcType=JdbcType.VARCHAR),
        @Result(column="zlwcx", property="zlwcx", jdbcType=JdbcType.VARCHAR),
        @Result(column="xlwcx", property="xlwcx", jdbcType=JdbcType.VARCHAR),
        @Result(column="dlwcjl", property="dlwcjl", jdbcType=JdbcType.VARCHAR),
        @Result(column="zlwcjl", property="zlwcjl", jdbcType=JdbcType.VARCHAR),
        @Result(column="xlwcjl", property="xlwcjl", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxll", property="maxll", jdbcType=JdbcType.VARCHAR),
        @Result(column="midll", property="midll", jdbcType=JdbcType.VARCHAR),
        @Result(column="minll", property="minll", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxcs", property="maxcs", jdbcType=JdbcType.VARCHAR),
        @Result(column="max02cs", property="max02cs", jdbcType=JdbcType.VARCHAR),
        @Result(column="mincs", property="mincs", jdbcType=JdbcType.VARCHAR)
    })
    Csfzk selectByPrimaryKey(Long id);

    @UpdateProvider(type=CsfzkSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Csfzk record);

    @Update({
        "update csfzk",
        "set zch = #{zch,jdbcType=VARCHAR},",
          "tmh = #{tmh,jdbcType=VARCHAR},",
          "scdh = #{scdh,jdbcType=VARCHAR},",
          "qjh = #{qjh,jdbcType=VARCHAR},",
          "jysj = #{jysj,jdbcType=TIMESTAMP},",
          "wd = #{wd,jdbcType=NUMERIC},",
          "sd = #{sd,jdbcType=VARCHAR},",
          "jyry = #{jyry,jdbcType=VARCHAR},",
          "shry = #{shry,jdbcType=VARCHAR},",
          "zgry = #{zgry,jdbcType=VARCHAR},",
          "dqyl = #{dqyl,jdbcType=NUMERIC},",
          "ysys = #{ysys,jdbcType=VARCHAR},",
          "zyls = #{zyls,jdbcType=NUMERIC},",
          "jl = #{jl,jdbcType=VARCHAR},",
          "wg = #{wg,jdbcType=VARCHAR},",
          "mfx = #{mfx,jdbcType=VARCHAR},",
          "xx = #{xx,jdbcType=VARCHAR},",
          "cfx = #{cfx,jdbcType=VARCHAR},",
          "jyrq = #{jyrq,jdbcType=TIMESTAMP},",
          "yxrq = #{yxrq,jdbcType=TIMESTAMP},",
          "zzfj = #{zzfj,jdbcType=VARCHAR},",
          "bw = #{bw,jdbcType=VARCHAR},",
          "ccbh = #{ccbh,jdbcType=VARCHAR},",
          "sccj = #{sccj,jdbcType=VARCHAR},",
          "xh = #{xh,jdbcType=VARCHAR},",
          "dj = #{dj,jdbcType=VARCHAR},",
          "wtdw = #{wtdw,jdbcType=VARCHAR},",
          "wtdwdz = #{wtdwdz,jdbcType=VARCHAR},",
          "zsh = #{zsh,jdbcType=VARCHAR},",
          "zzbh = #{zzbh,jdbcType=VARCHAR},",
          "maxl = #{maxl,jdbcType=NUMERIC},",
          "max2l = #{max2l,jdbcType=NUMERIC},",
          "minl = #{minl,jdbcType=NUMERIC},",
          "maxbz = #{maxbz,jdbcType=VARCHAR},",
          "maxb1 = #{maxb1,jdbcType=NUMERIC},",
          "maxb2 = #{maxb2,jdbcType=NUMERIC},",
          "maxb3 = #{maxb3,jdbcType=NUMERIC},",
          "maxb4 = #{maxb4,jdbcType=NUMERIC},",
          "maxb5 = #{maxb5,jdbcType=NUMERIC},",
          "maxb6 = #{maxb6,jdbcType=NUMERIC},",
          "maxb7 = #{maxb7,jdbcType=NUMERIC},",
          "maxb8 = #{maxb8,jdbcType=NUMERIC},",
          "maxb9 = #{maxb9,jdbcType=NUMERIC},",
          "maxb0 = #{maxb0,jdbcType=NUMERIC},",
          "max = #{max,jdbcType=NUMERIC},",
          "maxcz = #{maxcz,jdbcType=NUMERIC},",
          "max1 = #{max1,jdbcType=NUMERIC},",
          "max2 = #{max2,jdbcType=NUMERIC},",
          "max3 = #{max3,jdbcType=NUMERIC},",
          "max4 = #{max4,jdbcType=NUMERIC},",
          "max5 = #{max5,jdbcType=NUMERIC},",
          "max6 = #{max6,jdbcType=NUMERIC},",
          "max7 = #{max7,jdbcType=NUMERIC},",
          "max8 = #{max8,jdbcType=NUMERIC},",
          "max9 = #{max9,jdbcType=NUMERIC},",
          "max0 = #{max0,jdbcType=NUMERIC},",
          "maxbzyl1 = #{maxbzyl1,jdbcType=NUMERIC},",
          "maxbzyl2 = #{maxbzyl2,jdbcType=NUMERIC},",
          "maxbzyl3 = #{maxbzyl3,jdbcType=NUMERIC},",
          "maxbzyl4 = #{maxbzyl4,jdbcType=NUMERIC},",
          "maxbzyl5 = #{maxbzyl5,jdbcType=NUMERIC},",
          "maxbzyl6 = #{maxbzyl6,jdbcType=NUMERIC},",
          "maxbzyl7 = #{maxbzyl7,jdbcType=NUMERIC},",
          "maxbzyl8 = #{maxbzyl8,jdbcType=NUMERIC},",
          "maxbzyl9 = #{maxbzyl9,jdbcType=NUMERIC},",
          "maxbzyl0 = #{maxbzyl0,jdbcType=NUMERIC},",
          "maxbzwd1 = #{maxbzwd1,jdbcType=NUMERIC},",
          "maxbzwd2 = #{maxbzwd2,jdbcType=NUMERIC},",
          "maxbzwd3 = #{maxbzwd3,jdbcType=NUMERIC},",
          "maxbzwd4 = #{maxbzwd4,jdbcType=NUMERIC},",
          "maxbzwd5 = #{maxbzwd5,jdbcType=NUMERIC},",
          "maxbzwd6 = #{maxbzwd6,jdbcType=NUMERIC},",
          "maxbzwd7 = #{maxbzwd7,jdbcType=NUMERIC},",
          "maxbzwd8 = #{maxbzwd8,jdbcType=NUMERIC},",
          "maxbzwd9 = #{maxbzwd9,jdbcType=NUMERIC},",
          "maxbzwd0 = #{maxbzwd0,jdbcType=NUMERIC},",
          "maxbyl1 = #{maxbyl1,jdbcType=NUMERIC},",
          "maxbyl2 = #{maxbyl2,jdbcType=NUMERIC},",
          "maxbyl3 = #{maxbyl3,jdbcType=NUMERIC},",
          "maxbyl4 = #{maxbyl4,jdbcType=NUMERIC},",
          "maxbyl5 = #{maxbyl5,jdbcType=NUMERIC},",
          "maxbyl6 = #{maxbyl6,jdbcType=NUMERIC},",
          "maxbyl7 = #{maxbyl7,jdbcType=NUMERIC},",
          "maxbyl8 = #{maxbyl8,jdbcType=NUMERIC},",
          "maxbyl9 = #{maxbyl9,jdbcType=NUMERIC},",
          "maxbyl0 = #{maxbyl0,jdbcType=NUMERIC},",
          "maxbwd1 = #{maxbwd1,jdbcType=NUMERIC},",
          "maxbwd2 = #{maxbwd2,jdbcType=NUMERIC},",
          "maxbwd3 = #{maxbwd3,jdbcType=NUMERIC},",
          "maxbwd4 = #{maxbwd4,jdbcType=NUMERIC},",
          "maxbwd5 = #{maxbwd5,jdbcType=NUMERIC},",
          "maxbwd6 = #{maxbwd6,jdbcType=NUMERIC},",
          "maxbwd7 = #{maxbwd7,jdbcType=NUMERIC},",
          "maxbwd8 = #{maxbwd8,jdbcType=NUMERIC},",
          "maxbwd9 = #{maxbwd9,jdbcType=NUMERIC},",
          "maxbwd0 = #{maxbwd0,jdbcType=NUMERIC},",
          "max02bz = #{max02bz,jdbcType=VARCHAR},",
          "max02b1 = #{max02b1,jdbcType=NUMERIC},",
          "max02b2 = #{max02b2,jdbcType=NUMERIC},",
          "max02b3 = #{max02b3,jdbcType=NUMERIC},",
          "max02b4 = #{max02b4,jdbcType=NUMERIC},",
          "max02b5 = #{max02b5,jdbcType=NUMERIC},",
          "max02b6 = #{max02b6,jdbcType=NUMERIC},",
          "max02b7 = #{max02b7,jdbcType=NUMERIC},",
          "max02b8 = #{max02b8,jdbcType=NUMERIC},",
          "max02b9 = #{max02b9,jdbcType=NUMERIC},",
          "max02b0 = #{max02b0,jdbcType=NUMERIC},",
          "max02 = #{max02,jdbcType=NUMERIC},",
          "max02cz = #{max02cz,jdbcType=NUMERIC},",
          "max021 = #{max021,jdbcType=NUMERIC},",
          "max022 = #{max022,jdbcType=NUMERIC},",
          "max023 = #{max023,jdbcType=NUMERIC},",
          "max024 = #{max024,jdbcType=NUMERIC},",
          "max025 = #{max025,jdbcType=NUMERIC},",
          "max026 = #{max026,jdbcType=NUMERIC},",
          "max027 = #{max027,jdbcType=NUMERIC},",
          "max028 = #{max028,jdbcType=NUMERIC},",
          "max029 = #{max029,jdbcType=NUMERIC},",
          "max020 = #{max020,jdbcType=NUMERIC},",
          "max02bzyl1 = #{max02bzyl1,jdbcType=NUMERIC},",
          "max02bzyl2 = #{max02bzyl2,jdbcType=NUMERIC},",
          "max02bzyl3 = #{max02bzyl3,jdbcType=NUMERIC},",
          "max02bzyl4 = #{max02bzyl4,jdbcType=NUMERIC},",
          "max02bzyl5 = #{max02bzyl5,jdbcType=NUMERIC},",
          "max02bzyl6 = #{max02bzyl6,jdbcType=NUMERIC},",
          "max02bzyl7 = #{max02bzyl7,jdbcType=NUMERIC},",
          "max02bzyl8 = #{max02bzyl8,jdbcType=NUMERIC},",
          "max02bzyl9 = #{max02bzyl9,jdbcType=NUMERIC},",
          "max02bzyl0 = #{max02bzyl0,jdbcType=NUMERIC},",
          "max02bzwd1 = #{max02bzwd1,jdbcType=NUMERIC},",
          "max02bzwd2 = #{max02bzwd2,jdbcType=NUMERIC},",
          "max02bzwd3 = #{max02bzwd3,jdbcType=NUMERIC},",
          "max02bzwd4 = #{max02bzwd4,jdbcType=NUMERIC},",
          "max02bzwd5 = #{max02bzwd5,jdbcType=NUMERIC},",
          "max02bzwd6 = #{max02bzwd6,jdbcType=NUMERIC},",
          "max02bzwd7 = #{max02bzwd7,jdbcType=NUMERIC},",
          "max02bzwd8 = #{max02bzwd8,jdbcType=NUMERIC},",
          "max02bzwd9 = #{max02bzwd9,jdbcType=NUMERIC},",
          "max02bzwd0 = #{max02bzwd0,jdbcType=NUMERIC},",
          "max02byl1 = #{max02byl1,jdbcType=NUMERIC},",
          "max02byl2 = #{max02byl2,jdbcType=NUMERIC},",
          "max02byl3 = #{max02byl3,jdbcType=NUMERIC},",
          "max02byl4 = #{max02byl4,jdbcType=NUMERIC},",
          "max02byl5 = #{max02byl5,jdbcType=NUMERIC},",
          "max02byl6 = #{max02byl6,jdbcType=NUMERIC},",
          "max02byl7 = #{max02byl7,jdbcType=NUMERIC},",
          "max02byl8 = #{max02byl8,jdbcType=NUMERIC},",
          "max02byl9 = #{max02byl9,jdbcType=NUMERIC},",
          "max02byl0 = #{max02byl0,jdbcType=NUMERIC},",
          "max02bwd1 = #{max02bwd1,jdbcType=NUMERIC},",
          "max02bwd2 = #{max02bwd2,jdbcType=NUMERIC},",
          "max02bwd3 = #{max02bwd3,jdbcType=NUMERIC},",
          "max02bwd4 = #{max02bwd4,jdbcType=NUMERIC},",
          "max02bwd5 = #{max02bwd5,jdbcType=NUMERIC},",
          "max02bwd6 = #{max02bwd6,jdbcType=NUMERIC},",
          "max02bwd7 = #{max02bwd7,jdbcType=NUMERIC},",
          "max02bwd8 = #{max02bwd8,jdbcType=NUMERIC},",
          "max02bwd9 = #{max02bwd9,jdbcType=NUMERIC},",
          "max02bwd0 = #{max02bwd0,jdbcType=NUMERIC},",
          "minbz = #{minbz,jdbcType=VARCHAR},",
          "minb1 = #{minb1,jdbcType=NUMERIC},",
          "minb2 = #{minb2,jdbcType=NUMERIC},",
          "minb3 = #{minb3,jdbcType=NUMERIC},",
          "minb4 = #{minb4,jdbcType=NUMERIC},",
          "minb5 = #{minb5,jdbcType=NUMERIC},",
          "minb6 = #{minb6,jdbcType=NUMERIC},",
          "minb7 = #{minb7,jdbcType=NUMERIC},",
          "minb8 = #{minb8,jdbcType=NUMERIC},",
          "minb9 = #{minb9,jdbcType=NUMERIC},",
          "minb0 = #{minb0,jdbcType=NUMERIC},",
          "mincz = #{mincz,jdbcType=NUMERIC},",
          "min = #{min,jdbcType=VARCHAR},",
          "min1 = #{min1,jdbcType=VARCHAR},",
          "min2 = #{min2,jdbcType=NUMERIC},",
          "min3 = #{min3,jdbcType=NUMERIC},",
          "min4 = #{min4,jdbcType=NUMERIC},",
          "min5 = #{min5,jdbcType=NUMERIC},",
          "min6 = #{min6,jdbcType=NUMERIC},",
          "min7 = #{min7,jdbcType=NUMERIC},",
          "min8 = #{min8,jdbcType=NUMERIC},",
          "min9 = #{min9,jdbcType=NUMERIC},",
          "min0 = #{min0,jdbcType=NUMERIC},",
          "minbzyl1 = #{minbzyl1,jdbcType=NUMERIC},",
          "minbzyl2 = #{minbzyl2,jdbcType=NUMERIC},",
          "minbzyl3 = #{minbzyl3,jdbcType=NUMERIC},",
          "minbzyl4 = #{minbzyl4,jdbcType=NUMERIC},",
          "minbzyl5 = #{minbzyl5,jdbcType=NUMERIC},",
          "minbzyl6 = #{minbzyl6,jdbcType=NUMERIC},",
          "minbzyl7 = #{minbzyl7,jdbcType=NUMERIC},",
          "minbzyl8 = #{minbzyl8,jdbcType=NUMERIC},",
          "minbzyl9 = #{minbzyl9,jdbcType=NUMERIC},",
          "minbzyl0 = #{minbzyl0,jdbcType=NUMERIC},",
          "minbzwd1 = #{minbzwd1,jdbcType=NUMERIC},",
          "minbzwd2 = #{minbzwd2,jdbcType=NUMERIC},",
          "minbzwd3 = #{minbzwd3,jdbcType=NUMERIC},",
          "minbzwd4 = #{minbzwd4,jdbcType=NUMERIC},",
          "minbzwd5 = #{minbzwd5,jdbcType=NUMERIC},",
          "minbzwd6 = #{minbzwd6,jdbcType=NUMERIC},",
          "minbzwd7 = #{minbzwd7,jdbcType=NUMERIC},",
          "minbzwd8 = #{minbzwd8,jdbcType=NUMERIC},",
          "minbzwd9 = #{minbzwd9,jdbcType=NUMERIC},",
          "minbzwd0 = #{minbzwd0,jdbcType=NUMERIC},",
          "minbyl1 = #{minbyl1,jdbcType=NUMERIC},",
          "minbyl2 = #{minbyl2,jdbcType=NUMERIC},",
          "minbyl3 = #{minbyl3,jdbcType=NUMERIC},",
          "minbyl4 = #{minbyl4,jdbcType=NUMERIC},",
          "minbyl5 = #{minbyl5,jdbcType=NUMERIC},",
          "minbyl6 = #{minbyl6,jdbcType=NUMERIC},",
          "minbyl7 = #{minbyl7,jdbcType=NUMERIC},",
          "minbyl8 = #{minbyl8,jdbcType=NUMERIC},",
          "minbyl9 = #{minbyl9,jdbcType=NUMERIC},",
          "minbyl0 = #{minbyl0,jdbcType=NUMERIC},",
          "minbwd1 = #{minbwd1,jdbcType=NUMERIC},",
          "minbwd2 = #{minbwd2,jdbcType=NUMERIC},",
          "minbwd3 = #{minbwd3,jdbcType=NUMERIC},",
          "minbwd4 = #{minbwd4,jdbcType=NUMERIC},",
          "minbwd5 = #{minbwd5,jdbcType=NUMERIC},",
          "minbwd6 = #{minbwd6,jdbcType=NUMERIC},",
          "minbwd7 = #{minbwd7,jdbcType=NUMERIC},",
          "minbwd8 = #{minbwd8,jdbcType=NUMERIC},",
          "minbwd9 = #{minbwd9,jdbcType=NUMERIC},",
          "minbwd0 = #{minbwd0,jdbcType=NUMERIC},",
          "bz = #{bz,jdbcType=VARCHAR},",
          "dlwcx = #{dlwcx,jdbcType=VARCHAR},",
          "zlwcx = #{zlwcx,jdbcType=VARCHAR},",
          "xlwcx = #{xlwcx,jdbcType=VARCHAR},",
          "dlwcjl = #{dlwcjl,jdbcType=VARCHAR},",
          "zlwcjl = #{zlwcjl,jdbcType=VARCHAR},",
          "xlwcjl = #{xlwcjl,jdbcType=VARCHAR},",
          "maxll = #{maxll,jdbcType=VARCHAR},",
          "midll = #{midll,jdbcType=VARCHAR},",
          "minll = #{minll,jdbcType=VARCHAR},",
          "maxcs = #{maxcs,jdbcType=VARCHAR},",
          "max02cs = #{max02cs,jdbcType=VARCHAR},",
          "mincs = #{mincs,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Csfzk record);
    
    @Select({
        "select id,bw,zch,max,max02,min,xx,cfx,mfx,ysys,jl,jysj from csfzk order by id desc" 
    })
    @Results({
    	@Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="bw", property="bw", jdbcType=JdbcType.VARCHAR),
        @Result(column="zch", property="zch", jdbcType=JdbcType.VARCHAR),
        @Result(column="max", property="max", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02", property="max02", jdbcType=JdbcType.NUMERIC),
        @Result(column="min", property="min", jdbcType=JdbcType.VARCHAR),
        @Result(column="xx", property="xx", jdbcType=JdbcType.VARCHAR),
        @Result(column="cfx", property="cfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="mfx", property="mfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="ysys", property="ysys", jdbcType=JdbcType.VARCHAR),
        @Result(column="jl", property="jl", jdbcType=JdbcType.VARCHAR),
        @Result(column="jysj", property="jysj", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Csfzk> findAll();
    
    @Select({
        "select id,bw,zch,max,max02,min,xx,cfx,mfx,ysys,jl,jysj from csfzk",
        "where zch = #{meterCodeNum,jdbcType=VARCHAR} order by id"
    })
    @Results({
    	@Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="bw", property="bw", jdbcType=JdbcType.VARCHAR),
        @Result(column="zch", property="zch", jdbcType=JdbcType.VARCHAR),
        @Result(column="max", property="max", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02", property="max02", jdbcType=JdbcType.NUMERIC),
        @Result(column="min", property="min", jdbcType=JdbcType.VARCHAR),
        @Result(column="xx", property="xx", jdbcType=JdbcType.VARCHAR),
        @Result(column="cfx", property="cfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="mfx", property="mfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="ysys", property="ysys", jdbcType=JdbcType.VARCHAR),
        @Result(column="jl", property="jl", jdbcType=JdbcType.VARCHAR),
        @Result(column="jysj", property="jysj", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Csfzk> findByMeterCode(String meterCodeNum);
    
    // 通过表号查流量信息
    @Select({
        "select",
        "id, zch, tmh, scdh, qjh, jysj, wd, sd, jyry, shry, zgry, dqyl, ysys, zyls, jl, ",
        "wg, mfx, xx, cfx, jyrq, yxrq, zzfj, bw, ccbh, sccj, xh, dj, wtdw, wtdwdz, zsh, ",
        "zzbh, maxl, max2l, minl, maxbz, maxb1, maxb2, maxb3, maxb4, maxb5, maxb6, maxb7, ",
        "maxb8, maxb9, maxb0, max, maxcz, max1, max2, max3, max4, max5, max6, max7, max8, ",
        "max9, max0, maxbzyl1, maxbzyl2, maxbzyl3, maxbzyl4, maxbzyl5, maxbzyl6, maxbzyl7, ",
        "maxbzyl8, maxbzyl9, maxbzyl0, maxbzwd1, maxbzwd2, maxbzwd3, maxbzwd4, maxbzwd5, ",
        "maxbzwd6, maxbzwd7, maxbzwd8, maxbzwd9, maxbzwd0, maxbyl1, maxbyl2, maxbyl3, ",
        "maxbyl4, maxbyl5, maxbyl6, maxbyl7, maxbyl8, maxbyl9, maxbyl0, maxbwd1, maxbwd2, ",
        "maxbwd3, maxbwd4, maxbwd5, maxbwd6, maxbwd7, maxbwd8, maxbwd9, maxbwd0, max02bz, ",
        "max02b1, max02b2, max02b3, max02b4, max02b5, max02b6, max02b7, max02b8, max02b9, ",
        "max02b0, max02, max02cz, max021, max022, max023, max024, max025, max026, max027, ",
        "max028, max029, max020, max02bzyl1, max02bzyl2, max02bzyl3, max02bzyl4, max02bzyl5, ",
        "max02bzyl6, max02bzyl7, max02bzyl8, max02bzyl9, max02bzyl0, max02bzwd1, max02bzwd2, ",
        "max02bzwd3, max02bzwd4, max02bzwd5, max02bzwd6, max02bzwd7, max02bzwd8, max02bzwd9, ",
        "max02bzwd0, max02byl1, max02byl2, max02byl3, max02byl4, max02byl5, max02byl6, ",
        "max02byl7, max02byl8, max02byl9, max02byl0, max02bwd1, max02bwd2, max02bwd3, ",
        "max02bwd4, max02bwd5, max02bwd6, max02bwd7, max02bwd8, max02bwd9, max02bwd0, ",
        "minbz, minb1, minb2, minb3, minb4, minb5, minb6, minb7, minb8, minb9, minb0, ",
        "mincz, min, min1, min2, min3, min4, min5, min6, min7, min8, min9, min0, minbzyl1, ",
        "minbzyl2, minbzyl3, minbzyl4, minbzyl5, minbzyl6, minbzyl7, minbzyl8, minbzyl9, ",
        "minbzyl0, minbzwd1, minbzwd2, minbzwd3, minbzwd4, minbzwd5, minbzwd6, minbzwd7, ",
        "minbzwd8, minbzwd9, minbzwd0, minbyl1, minbyl2, minbyl3, minbyl4, minbyl5, minbyl6, ",
        "minbyl7, minbyl8, minbyl9, minbyl0, minbwd1, minbwd2, minbwd3, minbwd4, minbwd5, ",
        "minbwd6, minbwd7, minbwd8, minbwd9, minbwd0, bz, dlwcx, zlwcx, xlwcx, dlwcjl, ",
        "zlwcjl, xlwcjl, maxll, midll, minll, maxcs, max02cs, mincs",
        "from csfzk",
        "where zch = #{code,jdbcType=VARCHAR} order by id"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="zch", property="zch", jdbcType=JdbcType.VARCHAR),
        @Result(column="tmh", property="tmh", jdbcType=JdbcType.VARCHAR),
        @Result(column="scdh", property="scdh", jdbcType=JdbcType.VARCHAR),
        @Result(column="qjh", property="qjh", jdbcType=JdbcType.VARCHAR),
        @Result(column="jysj", property="jysj", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="wd", property="wd", jdbcType=JdbcType.NUMERIC),
        @Result(column="sd", property="sd", jdbcType=JdbcType.VARCHAR),
        @Result(column="jyry", property="jyry", jdbcType=JdbcType.VARCHAR),
        @Result(column="shry", property="shry", jdbcType=JdbcType.VARCHAR),
        @Result(column="zgry", property="zgry", jdbcType=JdbcType.VARCHAR),
        @Result(column="dqyl", property="dqyl", jdbcType=JdbcType.NUMERIC),
        @Result(column="ysys", property="ysys", jdbcType=JdbcType.VARCHAR),
        @Result(column="zyls", property="zyls", jdbcType=JdbcType.NUMERIC),
        @Result(column="jl", property="jl", jdbcType=JdbcType.VARCHAR),
        @Result(column="wg", property="wg", jdbcType=JdbcType.VARCHAR),
        @Result(column="mfx", property="mfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="xx", property="xx", jdbcType=JdbcType.VARCHAR),
        @Result(column="cfx", property="cfx", jdbcType=JdbcType.VARCHAR),
        @Result(column="jyrq", property="jyrq", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="yxrq", property="yxrq", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="zzfj", property="zzfj", jdbcType=JdbcType.VARCHAR),
        @Result(column="bw", property="bw", jdbcType=JdbcType.VARCHAR),
        @Result(column="ccbh", property="ccbh", jdbcType=JdbcType.VARCHAR),
        @Result(column="sccj", property="sccj", jdbcType=JdbcType.VARCHAR),
        @Result(column="xh", property="xh", jdbcType=JdbcType.VARCHAR),
        @Result(column="dj", property="dj", jdbcType=JdbcType.VARCHAR),
        @Result(column="wtdw", property="wtdw", jdbcType=JdbcType.VARCHAR),
        @Result(column="wtdwdz", property="wtdwdz", jdbcType=JdbcType.VARCHAR),
        @Result(column="zsh", property="zsh", jdbcType=JdbcType.VARCHAR),
        @Result(column="zzbh", property="zzbh", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxl", property="maxl", jdbcType=JdbcType.NUMERIC),
        @Result(column="max2l", property="max2l", jdbcType=JdbcType.NUMERIC),
        @Result(column="minl", property="minl", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbz", property="maxbz", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxb1", property="maxb1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb2", property="maxb2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb3", property="maxb3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb4", property="maxb4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb5", property="maxb5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb6", property="maxb6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb7", property="maxb7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb8", property="maxb8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb9", property="maxb9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxb0", property="maxb0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max", property="max", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxcz", property="maxcz", jdbcType=JdbcType.NUMERIC),
        @Result(column="max1", property="max1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max2", property="max2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max3", property="max3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max4", property="max4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max5", property="max5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max6", property="max6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max7", property="max7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max8", property="max8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max9", property="max9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max0", property="max0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl1", property="maxbzyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl2", property="maxbzyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl3", property="maxbzyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl4", property="maxbzyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl5", property="maxbzyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl6", property="maxbzyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl7", property="maxbzyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl8", property="maxbzyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl9", property="maxbzyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzyl0", property="maxbzyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd1", property="maxbzwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd2", property="maxbzwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd3", property="maxbzwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd4", property="maxbzwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd5", property="maxbzwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd6", property="maxbzwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd7", property="maxbzwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd8", property="maxbzwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd9", property="maxbzwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbzwd0", property="maxbzwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl1", property="maxbyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl2", property="maxbyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl3", property="maxbyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl4", property="maxbyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl5", property="maxbyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl6", property="maxbyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl7", property="maxbyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl8", property="maxbyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl9", property="maxbyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbyl0", property="maxbyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd1", property="maxbwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd2", property="maxbwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd3", property="maxbwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd4", property="maxbwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd5", property="maxbwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd6", property="maxbwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd7", property="maxbwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd8", property="maxbwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd9", property="maxbwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="maxbwd0", property="maxbwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bz", property="max02bz", jdbcType=JdbcType.VARCHAR),
        @Result(column="max02b1", property="max02b1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b2", property="max02b2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b3", property="max02b3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b4", property="max02b4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b5", property="max02b5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b6", property="max02b6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b7", property="max02b7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b8", property="max02b8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b9", property="max02b9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02b0", property="max02b0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02", property="max02", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02cz", property="max02cz", jdbcType=JdbcType.NUMERIC),
        @Result(column="max021", property="max021", jdbcType=JdbcType.NUMERIC),
        @Result(column="max022", property="max022", jdbcType=JdbcType.NUMERIC),
        @Result(column="max023", property="max023", jdbcType=JdbcType.NUMERIC),
        @Result(column="max024", property="max024", jdbcType=JdbcType.NUMERIC),
        @Result(column="max025", property="max025", jdbcType=JdbcType.NUMERIC),
        @Result(column="max026", property="max026", jdbcType=JdbcType.NUMERIC),
        @Result(column="max027", property="max027", jdbcType=JdbcType.NUMERIC),
        @Result(column="max028", property="max028", jdbcType=JdbcType.NUMERIC),
        @Result(column="max029", property="max029", jdbcType=JdbcType.NUMERIC),
        @Result(column="max020", property="max020", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl1", property="max02bzyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl2", property="max02bzyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl3", property="max02bzyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl4", property="max02bzyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl5", property="max02bzyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl6", property="max02bzyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl7", property="max02bzyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl8", property="max02bzyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl9", property="max02bzyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzyl0", property="max02bzyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd1", property="max02bzwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd2", property="max02bzwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd3", property="max02bzwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd4", property="max02bzwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd5", property="max02bzwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd6", property="max02bzwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd7", property="max02bzwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd8", property="max02bzwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd9", property="max02bzwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bzwd0", property="max02bzwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl1", property="max02byl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl2", property="max02byl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl3", property="max02byl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl4", property="max02byl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl5", property="max02byl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl6", property="max02byl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl7", property="max02byl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl8", property="max02byl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl9", property="max02byl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02byl0", property="max02byl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd1", property="max02bwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd2", property="max02bwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd3", property="max02bwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd4", property="max02bwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd5", property="max02bwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd6", property="max02bwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd7", property="max02bwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd8", property="max02bwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd9", property="max02bwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="max02bwd0", property="max02bwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbz", property="minbz", jdbcType=JdbcType.VARCHAR),
        @Result(column="minb1", property="minb1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb2", property="minb2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb3", property="minb3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb4", property="minb4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb5", property="minb5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb6", property="minb6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb7", property="minb7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb8", property="minb8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb9", property="minb9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minb0", property="minb0", jdbcType=JdbcType.NUMERIC),
        @Result(column="mincz", property="mincz", jdbcType=JdbcType.NUMERIC),
        @Result(column="min", property="min", jdbcType=JdbcType.VARCHAR),
        @Result(column="min1", property="min1", jdbcType=JdbcType.VARCHAR),
        @Result(column="min2", property="min2", jdbcType=JdbcType.NUMERIC),
        @Result(column="min3", property="min3", jdbcType=JdbcType.NUMERIC),
        @Result(column="min4", property="min4", jdbcType=JdbcType.NUMERIC),
        @Result(column="min5", property="min5", jdbcType=JdbcType.NUMERIC),
        @Result(column="min6", property="min6", jdbcType=JdbcType.NUMERIC),
        @Result(column="min7", property="min7", jdbcType=JdbcType.NUMERIC),
        @Result(column="min8", property="min8", jdbcType=JdbcType.NUMERIC),
        @Result(column="min9", property="min9", jdbcType=JdbcType.NUMERIC),
        @Result(column="min0", property="min0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl1", property="minbzyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl2", property="minbzyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl3", property="minbzyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl4", property="minbzyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl5", property="minbzyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl6", property="minbzyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl7", property="minbzyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl8", property="minbzyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl9", property="minbzyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzyl0", property="minbzyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd1", property="minbzwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd2", property="minbzwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd3", property="minbzwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd4", property="minbzwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd5", property="minbzwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd6", property="minbzwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd7", property="minbzwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd8", property="minbzwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd9", property="minbzwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbzwd0", property="minbzwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl1", property="minbyl1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl2", property="minbyl2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl3", property="minbyl3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl4", property="minbyl4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl5", property="minbyl5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl6", property="minbyl6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl7", property="minbyl7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl8", property="minbyl8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl9", property="minbyl9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbyl0", property="minbyl0", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd1", property="minbwd1", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd2", property="minbwd2", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd3", property="minbwd3", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd4", property="minbwd4", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd5", property="minbwd5", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd6", property="minbwd6", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd7", property="minbwd7", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd8", property="minbwd8", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd9", property="minbwd9", jdbcType=JdbcType.NUMERIC),
        @Result(column="minbwd0", property="minbwd0", jdbcType=JdbcType.NUMERIC),
        @Result(column="bz", property="bz", jdbcType=JdbcType.VARCHAR),
        @Result(column="dlwcx", property="dlwcx", jdbcType=JdbcType.VARCHAR),
        @Result(column="zlwcx", property="zlwcx", jdbcType=JdbcType.VARCHAR),
        @Result(column="xlwcx", property="xlwcx", jdbcType=JdbcType.VARCHAR),
        @Result(column="dlwcjl", property="dlwcjl", jdbcType=JdbcType.VARCHAR),
        @Result(column="zlwcjl", property="zlwcjl", jdbcType=JdbcType.VARCHAR),
        @Result(column="xlwcjl", property="xlwcjl", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxll", property="maxll", jdbcType=JdbcType.VARCHAR),
        @Result(column="midll", property="midll", jdbcType=JdbcType.VARCHAR),
        @Result(column="minll", property="minll", jdbcType=JdbcType.VARCHAR),
        @Result(column="maxcs", property="maxcs", jdbcType=JdbcType.VARCHAR),
        @Result(column="max02cs", property="max02cs", jdbcType=JdbcType.VARCHAR),
        @Result(column="mincs", property="mincs", jdbcType=JdbcType.VARCHAR)
    })
 	Csfzk findByCode(String code);
    
}